#
#
#

test_pearl: pearl.c
	gcc -D TESTCODE -D _VSCODE -Wall pearl.c dummyTask/dummyTask1.c dumtask2/dummyTask2.c ../pearl621.c ../pearl621_intr.c ../pearl621_task.c ../pearl621_chatter.c -o test_pearl

